pr: none
trigger:
  batch: false
  branches:
    include:
    - main

pool:
  name: Azure Pipelines
steps:
- task: UseDotNet@2
  inputs:
    version: '3.x' # Replace with the required .NET Core SDK version
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.json' # Adjust the pattern to match your ARM templates and other files.
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ARM'

#publish the artifacts

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: MyArtifacttest'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/ARM'  # Adjust the path as per your output directory
    ArtifactName: 'MyArtifacttest'

